### ISSUE TITLE
marketing_permission tag is not rendered when customer is not logged in

### ISSUE THREAD

**Issue by diazwatson** [Nosto/nosto-magento2#608] opened 2019-11-22 17:27 UTC
**Is your feature request related to a problem? Please describe.**

> By default Nosto's Magento 2 extension uses Magento's newsletter subscription as a source of information for populating this field. In other words, if a customer is also a newsletter subscriber marketing_permission field will be set to true and Nosto considers that the customer has given GDPR compliant marketing permission consent. If a customer is not a newsletter subscriber marketing_permission field will be set to false and Nosto considers that the customer has not given GDPR compliant marketing permission.

According to what we see in:
```
vendor/nosto/module-nostotagging/CustomerData/CustomerTagging.php::getSectionData()
```
and in:
```
vendor/nosto/module-nostotagging/view/frontend/templates/customer.phtml:60
```
This only happens if customer is logged in. If customer is not logged in, no tags are rendered and therefore this information never reach Nosto.

**Describe the solution you'd like**

Would not be better to make these tags independent? 

**Describe alternatives you've considered**

Render tha tags all the time and fill the values with data as it is available. 

**Additional context**

What you guys think about this?
Does this make sense?
Is there a better way to handle this?

We are currently using version 3.8.0

**Comment by hannunosto** [comment] 2019-11-25 07:45
Hi @diazwatson, can you elaborate a bit. If a visitor is not logged in we don't know the email address of the visitor. Basically we don't need marketing permission for an anonymous visitor as we don't know the email address where to bind the marketing permission to. 

Or maybe I'm missing something?

**Comment by diazwatson** [comment] 2019-11-26 10:01
@hannunosto thanks for taking the time to reply to my message.

In my example I was referring to those cases where the visitor make a purchase without registering an account. In those cases we know the email address because it has been provided during the checkout process.

Another case: Visitors that have provided their email address in the box _subscribe to the newsletter_
They not necessarily need to be logged in or have an account in Magento in order to be subscribed to the newsletter?

What happen with the tags in Nosto tags in those cases?

**Comment by hannunosto** [comment] 2019-11-26 11:11
No worries @diazwatson. Thanks for the clarification. You have valid points there. 

Nosto however does not process / save customer related data (email, name, marketing permission, etc.) unless the data is inside "customer tagging" (https://github.com/Nosto/nosto-magento2/blob/develop/view/frontend/templates/customer.phtml). Customer tagging is only rendered when visitor is logged in. This means that we cannot use the marketing permission without customer logged in. 

During the order confirmation we tag the customer inside the order tagging and this customer object also has the marketing permission attribute. If the visitor has agreed to signup to newsletter during the checkout process we will tag the marketing permission as true. 

I'll close this issue for now but please do let us know if the explanation above is not sufficient or we are still missing something.

**Closed by hannunosto** 2019-11-26 11:11 UTC
Labels: enhancement, question

**Comment by diazwatson** [comment] 2019-11-26 11:36
Many thanks @hannunosto for your explanation.

Just to double check and confirm, by what you are saying I understand that there is no need to customise and extend the Nosto module in order to render these tags during the checkout (when a customer is not logged in). That is because the module already takes care of this by using the subscription information included in the order tag. Is that correct?

One final question, is there a way to test the order tagging using the debug tool? (?nostodebug=true)
Maybe in the success page?

**Comment by hannunosto** [comment] 2019-11-27 07:26
@diazwatson you are right. The module will take care of the customer tagging, order tagging, etc. automatically. In most cases there's no need to do any customizations / overrides to the module.

As you suggested you can verify that the tagging is correct by adding `nostodebug=true` parameter to any URL. This will invoke the debug toolbar and it will stay visible until you explicitly close it. Naturally you can not refresh the success page so make sure you invoke the debug toolbar before you enter the checkout process.  

Here's an example how the  debug toolbar should look like on success page: 
<img width="1419" alt="Success_Page" src="https://user-images.githubusercontent.com/15191701/69702049-0714ed80-10f7-11ea-990f-38841805660c.png">

**Comment by diazwatson** [comment] 2019-11-27 12:12
Many thanks for helping us out with this @hannunosto 

I have tested and certainly I can see the information being extracted from the order tags as you described. That is great.

For this particular test I have placed an order with a non registered customer and Opted In to be subscribed to the newsletter.

![Screenshot 2019-11-27 at 11 12 58](https://user-images.githubusercontent.com/1080386/69720225-089be100-110a-11ea-9ce5-049986ea93ca.png)

But when testing the values with the debugging tool I see `marketing_permission` being set to `No`.

At the same time if I inspect the code I can see how `marketing_permission` tag has `1` value. 

I believe this is because I would need to reload the page for this information to be updated in the debugging tool (but obviously if I do then the session is going to be lost).

Now, from what I can see, this should not make any difference. 

I mean, even when the value of `marketing_permission` is not updated in the debugging tool, we still should get `1` value in Nosto side (along with the rest of the order info), because that is the value the tag has.

Could you confirm this?

**Comment by hannunosto** [comment] 2019-11-28 08:12
Good catch @diazwatson! It seems the issue is in the debug toolbar and not in the module or in the tagging. I'll let our dev team know about the debug toolbar issue.

To sum it up the marketing permission gets tagged and saved correctly in Nosto. The only issue is the debug toolbar that doesn't show the status correctly.

**Comment by diazwatson** [comment] 2019-11-29 14:17
Thanks @hannunosto

**Comment by hannunosto** [comment] 2019-12-10 12:26
Sorry for the delay in getting back to this. The debug toolbar is now also fixed.

**Comment by diazwatson** [comment] 2019-12-13 11:08
Great news @hannunosto 
Thanks for the update
