### ISSUE TITLE
Product Indexer causes process to run out of memory

### ISSUE THREAD

**Issue by hrle991** [Nosto/nosto-magento2#229] opened 2018-02-21 12:28 UTC
Magento EE 2.2.2
Latest Nosto ver. 2.6.1
Catalog size: 24 000 skus

Full reindex from cli throws this error: 

> SQLSTATE[HY000]: General error: 5 Out of memory (Needed 3140263920 bytes), query was: SELECT COUNT(DISTINCT e.entity_id) FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_entity_int` AS `at_status_default` ON (`at_status_default`.`row_id` = `e`.`row_id`) AND (`at_status_default`.`attribute_id` = '96') AND `at_status_default`.`store_id` = 0
 LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`row_id` = `e`.`row_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 1)
 INNER JOIN `catalog_product_entity_int` AS `at_visibility_default` ON (`at_visibility_default`.`row_id` = `e`.`row_id`) AND (`at_visibility_default`.`attribute_id` = '102') AND `at_visibility_default`.`store_id` = 0 WHERE ((IF(at_status.value_id > 0, at_status.value, at_status_default.value) = 1)) AND (e.created_in <= '1516524480') AND (e.updated_in > '1516524480')

**Comment by hannunosto** [comment] 2018-02-22 07:54
Thanks for reporting this @hrle991. It seems MySQL runs out of memory. To verify and pinpoint the issue can you try to limit the max page size (https://github.com/Nosto/nosto-magento2/blob/develop/Model/Indexer/Product/Indexer.php#L24) to, let's say 10 000 or something lower and let us know if it helped.

As a temporary fix you can also raise the limit how much memory MySQL can consume.

**Comment by hrle991** [comment] 2018-02-23 10:48
Hi @hannunosto, 

thanks for the reply, unfortunately lowering value for the HARD_LIMIT_FOR_PRODUCTS const doesn't seem to help. Also, I don't think that raising MySQL memory limit that high is an option.

**Comment by hannunosto** [comment] 2018-02-26 07:05
Ok, thanks @hrle991. Could you please post the full stack trace here. If lowering the max page size didn't have any effect we need to dig a bit deeper what is the cause of this error.

**Comment by hannunosto** [comment] 2018-03-16 08:18
Closing this due to no activity

**Comment by mridang** [comment] 2018-06-06 09:26
@hrle991 We found the issue. Apologies for closing the issue so hastily earlier. 🙏 Please see the pull-request.

**Closed** 2018-06-06 13:27 UTC
Labels: bug
