### ISSUE TITLE
Error saving products in admin

### ISSUE THREAD

**Issue by igor-imaginemage** [Nosto/nosto-magento2#475] opened 2019-06-03 19:53 UTC
Hi guys,

updating products on admin I'm receiving an error saying:

"Could not save product "" with position 0 to category 3"

It's about the association between products and categories.

https://www.loom.com/share/42ba3310bec84648910a3110a2ae86e4

If we disable Nosto extension, the error disappear.

Debugging the code, I see the problem is happening in vendor/magento/module-catalog/Model/CategoryLinkRepository.php inside the methods deleteByIds and save. They are using the productRepository class to load the product, this method to load the product by the sku (get) try to get the product from the cache, and if not available it gets from the database.

By some reason when Nosto is enabled Magento is always returning the product from cache, but without any product data. That's why the error is happening.

This is happening with us in Magento Enterprise 2.2.6.

**Comment by hannunosto** [comment] 2019-06-05 08:55
Hi @igor-imaginemage, thanks for reporting this. Unfortunately we could not reproduce the issue. Nosto's product update however runs before the category links are removed from the database so it might be related to that. 

Did you just create the product and / or the category and then remove a category from the product?

Could you provide us exact steps to reproduce the issue.

**Comment by alexdevanna** [comment] 2019-06-06 11:38
We've also reproduced in 2.2.6, Nosto v 3.7.3.

**Comment by igor-imaginemage** [comment] 2019-06-06 12:01
Hi @hannunosto, it's editing a product. We create a product and after that we try to edit the product assigning new categories or removing categories.

**Comment by hannunosto** [comment] 2019-06-07 06:36
Thanks @igor-imaginemage @alexdevanna, we found the issue and it's now fixed in 3.7.5 (https://github.com/Nosto/nosto-magento2/releases/tag/3.7.5)

**Closed by hannunosto** 2019-06-07 06:36 UTC
Labels: bug

**Comment by igor-imaginemage** [comment] 2019-06-07 12:20
Thank you @hannunosto, I'll test this new release version.
